### ISSUE TITLE
Add more details to experiment

### ISSUE THREAD

**Issue by calebcauthon** [panasandiego/idea-library#12]
- [x] Location
- [x] Policies
- [x] Start / End / Ongoing
- [ ] Twitter Hashtag (moving to a new issue)

![image](https://cloud.githubusercontent.com/assets/148787/12368380/d5e9a214-bc4f-11e5-8de1-1870a04cb562.png)

![image](https://cloud.githubusercontent.com/assets/148787/12368394/f06c9222-bc4f-11e5-95e9-4cf03b5ab7e1.png)

![image](https://cloud.githubusercontent.com/assets/148787/12368407/0e762e40-bc50-11e5-9d37-c8a09de5a03c.png)

![image](https://cloud.githubusercontent.com/assets/148787/12368436/3b458f88-bc50-11e5-9709-cf7a1670b5b8.png)

**Comment by calebcauthon** [comment]
@baisong I'm not seeing the connection between policies and experiments in the data:

![image](https://cloud.githubusercontent.com/assets/148787/12363743/54e63256-bc2f-11e5-855c-321907ea20d6.png)

**Comment by baisong** [comment]
Experiments and policies are both node types, so each one has a unique node ID.

Experiments are instances of policies-- each experiment will have one value for the "field_idea_model" property, which refers to the policy by it's node ID (record ID).

**Comment by calebcauthon** [comment]
@baisong great, I've added screenshots to the top of this thread. Policies and experiments are now connected.
