### ISSUE TITLE
Navigation by issues & places

### ISSUE THREAD

**Issue by baisong** [panasandiego/idea-library#27]
We want these 2 ways to explore campaigns for now: issues (i.e. "Mass Incarceration"), and places (i.e. "San Diego, CA").

Here's the mockup of this navigation, starting with "Issues" in a tile/grid display:

- https://app.moqups.com/get.oren@gmail.com/n6rJi1sreq/view/page/ab9f3decb

**Comment by calebcauthon** [comment]
@baisong done!

**Comment by calebcauthon** [comment]
@baisong done! #29 and #30
